// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

import Navigation from "@/components/Navigation"

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


// export const metadata = {
//   title: 'my-project',
//   description: '...',
// }


export const metadata = {
  title: {
    template: '%s | learning-nextjs',
    /***so ye "%s" ki help se jo bhi metadata ka title hum kisi individual page  mein denge
     * woh title iss %s ki jagah aajayega aur agar kisi page mein metadata nhi hoga toh udhar
     * title mein default:"my-project" aajayega
      */
    default: 'myproject', // a default is required when creating a template
  },
}




function RootLayout({children}){
  return(
    <html>
      <body>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}

export default RootLayout